<a id='top'></a>
# Day 1.1: Python Data Types
Date: 03/10/2022
Author: Aaron Watt

Goal: Discuss different types of data structures in Python and explore their (sometimes strange) behavior. We will
- [Part 1](#basic_types): List out many python data types, and quickly examine a few
- [Part 2](#loops): Compare two values, if-else statements, loops, and "scope"
- [Part 3](#iterable_types): Examine iterable data types
- [Part 4](#numpy): Discuss NumPy datatypes in more detail
- [Part 5](#matrix): Use NumPy matrices for matrix algebra

<a id='basic_types'></a>
## Part 1: Basic python data types
Every language has slightly different ways of storing information/data (data types). Each language also has it's own rules that go along with those data types. Let's start with the most common data types for python:

- Text Type: `str`
- Numeric Types: `int`, `float`, `complex`
- Sequence Types: `list`, `tuple`, `range`
- Set Types: `set`, `frozenset`
- Mapping Type: `dict`
- Boolean Type: `bool` (true or false)
- Binary Types: `bytes`, `bytearray`, `memoryview` (1 or 0)


The most common ones you'll probably use during ARE 212 are:
- `str`
- `bool`
- `bytes`
- `int`, `float`
- LOOP BREAK
- `list`, `tuple`, `range`
- `set`
- `dict`

Let's go through them real quick!


[More on python data types](https://www.w3schools.com/python/python_datatypes.asp)

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<div class="alert alert-block alert-info">
<b>Aside on python object names:</b><br>
<ul>
  <li>Everything in python is an object and names in python point to these objects in memory.</li>
  <li>If you name two different objects with the same name, the second time you name it will override the first.</li>
  <li>There are exceptions for ^same names^, but we'll be talking about that later (scope).</li>
  <li>You cannot name something starting with numbers, but you can put number elsewhere in the name.</li>
  <li>Dots (.) have special use in python and cannot be used in names. They will be used at the end of names to do special things.</li>
</ul>
 
</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

### Examples of Data Types

#### Strings
A `str` is a list of characters.

In [ ]:
str1 = "h"
str1 = 'h'  # you can use either single '' or double quotes ""
str2 = "3"
str3 = ""   # empty string!
str4 = "ARE 212 Rocks!"

We can combine strings in a few ways

In [ ]:
str5 = str1 + str2
print(str5)

str6 = ', '.join([str1, str2])
print(str6)

<br><br>

<div class="alert alert-block alert-info">
<b>Assignment:</b> Notice that we're using = to assign values to names.
</div>

<br>

<div class="alert alert-block alert-info">
<b>Types, Classes, Methods, and Functions:</b> We'll get into these definitions later. But for now, note the following: all objects have "types" (string, integer, float, ...), and objects are created by "classes". When we create a string object, there is a class in the background that is smooshing all the characters together into one object. Object classes also have "methods" associated with them. These are functions that are run on the object to return a result. Below, I give some examples of string methods that return useful information about the string. We'll come back to the idea of functions, classes, and methods in the future.
</div>

method syntax: `object.method()`

Some important string methods. [More in this W3 Schools list](https://www.w3schools.com/python/python_ref_string.asp)

In [ ]:
s = "testCaptializing is fun"

# Capitalization
print("\n\n",s)
print(".upper() returns this:", s.upper())
print("\n.lower() returns this:", s.lower())
print("\n.title() returns this:", s.title())

<br><br>

In [ ]:
# Splitting
s = "Let's Split some strings!"
print("\n\n",s)
print(".split() returns this:", s.split())
print("\n.split(' ') returns this:", s.split(' '))
print("\n.split(',') returns this:", s.split(','))

<br><br>

In [ ]:
# Stripping whitespace and other characters
s = "Kesha is fun"
print("\n\n",s)
print(".strip() returns this:", s.strip())
print("\n.strip(' fun') returns this:", s.strip(' fun'))
print("\n.replace(' ', '') returns this:", s.replace(' ', ''))
print("\n.replace('s', '$') returns this:", s.replace('s', '$'))

<br><br>

In [ ]:
# String information
s = "get me some info"
print("\n\n",s)
print(".find('m') returns this:", s.find('m'))
print("\n.rfind('m') returns this:", s.rfind('m'))
print("\n.count('m') returns this:", s.count('m'))
print("\n.isalpha() returns this:", s.isalpha())
print("\n.isalpha() returns this:", s.replace(' ', '').isalpha())

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___
#### Integers
An `int` is an integer (can be zero or negative)

In [ ]:
int1 = 0
int2 = -500
int3 = 10**10  # 10^10

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___
#### Floats
A `float` is a real number (with decimal points). Beware of rounding errors.

In [ ]:
float1 = 1.1
float2 = 1e3  # 1*10^3

Python automatically converts integers to floats if we do math with the integers that should return a float:

In [ ]:
float3 = 1 / 2
print(float3)

We can also round floats to some amount of precision

In [86]:
print(round(2.123456))
print(round(2.123456, 3))

2
2.123


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___
#### None type
`None` is a special python type. It is just a placeholder for "nothing". Along with empty strings (`""`), `None` is often used as a placeholder for default values that then get replaced.

In [73]:
print(None)

None


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___
#### Boolean Values
Boolean Values are `True`/`False` values. These are used often with `if` statements. These will be useful in `for` loops that we get into later.

In [ ]:
is_aaron_silly = True
if is_aaron_silly:
    print('I KNEW IT... aaron is silly')

<br>

In [85]:
# We can negate boolean values with `not` and `not()`
print(not(True))

if False is not True:
    print("that's ... uhhh.. true?")

False
that's ... uhhh.. true?


<br><br>
What's the difference between `is` and `==`?

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___
#### Bytes
Bytes ... know that they exist as a special way to encode information. You mostly need to know what they are in case an error occurs that tells you something about
<span style="color:red">encoding</span> or <span style="color:red">Bytes-like objects</span>.

In [ ]:
print(bytes(2))
print(bytes('a', 'utf-8'))
print(bytes([1,2,3]))

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>[top of page](#top)

<a id='loops'></a>
## Part 2: Comparisons, Conditionals, Loops, and Scope in python

We often combine loops and conditionals to exit loops when certain criteria are met. One example we'll use next section: we write code to minimize an objective function. Sometimes the problem is complicated and we need to search for a minimizing value. We iterate using loops to get smaller and smaller values, but we need conditionals to know when to exit the loop when we've gotten sufficiently minimized. Lets look at some examples.



### Python comparison operators
[Comparison operators tutorial](https://www.tutorialspoint.com/python/comparison_operators_example.htm)

We need to know how to compare values in python. Comparison operators compare two or more objects and returns a boolean value (`True/False`). Here's the basics:

In [70]:
# Is equal to?
print(1 == 2)
print('a' == 'a')

False
True


In [71]:
# Not equal to?
print('a' != 'b')

True


In [87]:
# Less than, greater than, etc.
print(1 < 2)
print(1 <= 2)
print(2 <= 2)
print(2 > 2)

True
True
True
False


<br><br>

### Conditionals
Conditional statements: `if-else` statements are critical in many situations to help us choose different actions when the inputs have changed.

We'll be quick here. They do what you think, but here's a few examples so you can see the syntax. If you want more examples, see the 
[RealPython conditionals tutorial](https://realpython.com/python-conditional-statements/).




**Syntax**
```python
# Python basic if statement
if <expr>:
    <statement>

    
    
# if with an else clause
if <expr>:
    <statement(s)>
else:
    <statement(s)>

    
    
# if with a elif and else clause
# all these are mutually exclusive expressions, checking from top to bottom
if <expr>:
    <statement(s)>
elif <expr>:
    <statement(s)>
elif <expr>:
    <statement(s)>
    ...
else:
    <statement(s)>
```

<br><br>

**Examples**

In [ ]:
# Use an if statement by itself
s = "abigail"
if s == "Abigail":
    print("This is Abigail")

<br><br>

In [ ]:
# Use if, then else to catch everything else
s = "abigail"
if s == "Abigail":
    print("This is Abigail")
else:
    print("Imposter! Close but not Abigail!")

<br><br>

In [ ]:
# Multiple cases
s = "abigail"
if s == "Abigail":
    print("This is Abigail")
elif s.lower() == "Abigail".lower():
    print("This is technically Abigail, but watch your capitalization")
else:
    print("Imposter! Close but not Abigail!")

<br><br>

In [ ]:
x = 9
if x < 5:
    print('x < 5')
elif x == 5:
    print('x = 5')
elif x < 7:
    print('5 < x < 6')
else:
    print('x >= 7')

<br><br>
This might seem cumbersome for piecewise functionality. Sometimes we can improve on this by using dictionaries to solve a problem where we have many specific cases and need to find an answer for just one. We'll talk about dictionaries below. In python 3.10, we can actually use "pattern matching" to break out these cases. See this [this StackOverflow post](https://stackoverflow.com/a/11479840) for an explanation.

<br><br><br><br><br><br>

### What if two values are close but not exactly the same?
The python `math` package can help! It returns `True` if two values are close.

In [ ]:
import math
x = 1.0000001
if math.isclose(1, x):
    print("Basically the same")
else:
    print("NOPE: Different enough ¯\_(ツ)_/¯")

<br><br>
But how close is close? The default "relative difference" is 1e-09. This can be changed by setting the `rel_tol` value.

In [ ]:
print(math.isclose(1, 1.0000001, rel_tol=0.001))
print(math.isclose(1, 1.0000001, rel_tol=1e-10))

<br><br><br>
<div class="alert alert-block alert-warning">
<b>Aside on whitespace indentation in Python:</b> Note that all the if-else statements above are indented. Python is a <b>whitespace-sensitive language</b> and MUST be properly indented to execute. Run the below code chunk to see what happens when you have improper indentation.
</div>

[See this nice StackOverflow answer about whitespace in python.](https://stackoverflow.com/a/13884583)

In [ ]:
if True is True:
    print('this is true')    # indented 4 spaces
      print('this is true')  # indented 6 spaces

<br><br><br><br><br>

### While Loops

[GeeksForGeeks loops tutorial](https://www.geeksforgeeks.org/loops-in-python/)

While loops look similar to conditional if statements. They keep running what is in the loop until the exit criteria is met. The syntax looks like:
<br>
```python
while [exit criteria here]:
    [do something in loop here]

print("this prints after the loop exits")
```

The exit criteria must return a boolean value (true/false) and needs to be something that the loop changes. If the loop does not change the value of the exit criteria, the loop will continue forever.

In [ ]:
from time import sleep  # this is not necessary, just helpful for the tutorial
while True:
    print("this is true.")
    sleep(1)  # pause for 1 second

In [ ]:
x = 9

while x > 0:
    print(x)
    x = x - 1
    sleep(0.5)

print("Finished")

<br><br>

### For Loops
For loops iterate over things that have multople elements (iterable objects). We'll talk about these more next, but consider a list of items called `list1` that we want to print all the values for. The basic syntax would look like this:
```python
list1 = [some list of items]

for myitem in list1:
    [do something in loop with myitem]

```

The beginning of the for loops says "`for i in list1`. The `for` and `in` are required. The first time the loop runs, the object `myitem` is created and is equal to the first element in the list `list1`. Then, for each time the loop repeats, it overwrites `myitem` with the next value in `list1`. This does not do anything to `list1`, it is just reading the values.
<br>
<br>
Some examples:

In [94]:
list1 = [1, 2, 3, 4]

for item in list1:
    print(item)

1
2
3
4


<br>

In [67]:
# we can use any non-existing name for the inner variable
for i in list1:
    j = i**2
    print(i,j)

1 1
2 4
3 9
4 16


<br>

In [89]:
# what if we want to skip a loop?
for i in [1, 2, 3, 4]:
    if i == 2:
        continue  # this skips the rest of the code inside the loop
    print(i)


1
3
4


<br>

In [90]:
# what if we want to leave a loop early?
for i in [1, 2, 3, 4]:
    if i == 2:
        break  # this exits the existing loop
    print(i)

1


<br>

In [95]:
# Multi-dimensional looping (loops in loops -- LOOPCEPTION!)
for i in [1, 2, 3, 4]:
    for j in ['a', 'b', 'c']:
        print(i, j)

1 a
1 b
1 c
2 a
2 b
2 c
3 a
3 b
3 c
4 a
4 b
4 c


<br>

In [90]:
# what if we want to leave a loop early?
for i in [1, 2, 3, 4]:
    if i == 2:
        break  # this exits the existing loop
    print(i)

1


<br>

In [96]:
# What if we leave a loop that's inside another loop?
for i in [1, 2, 3, 4]:
    for j in ['a', 'b', 'c']:
        if j == 'b':
            break  # this exits the inside loop
        print(i, j)

1 a
2 a
3 a
4 a


<br><br><br>
<div class="alert alert-block alert-info">
<b>Shouldn't I just use a while loop if I want to break?</b> The examples above are meant to be simple for exposition. In reality, there are many cases when we have a complex for loop, and we realize that we need to break out of it if we match some complicated condition or get an error. A while loop works great for simple situations, but often conditionals inside the for loop are the most straightforward way to write the code.
</div>

<br>

<br><br><br><br><br><br><br><br>

x1: a
i: 1
j: there
x1: a
i: 2
j: there
x1: a
i: 3
j: there
x1: a
i: 4
j: there
there
4
8


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>[top of page](#top)

<a id='iterable_types'></a>
## Part 3: Iterable Objects (lists, tuples, ranges, sets, dictionaries)
Iterable objects are object that can be iterated over. These types allows us to build up to matrix algebra in the next section.

#### Lists
A `list` is an ordered bag of python objects. You can imagine putting a bunch of integers, floats, or strings into a list:

In [ ]:
list1 = [1, 2, 3]
list2 = ["a", "b", "twenty three"]

You can also imagine putting a mix of items into a list (integer, string, float):

In [ ]:
list3 = [1, "b", 1.1]

You can even put lists inside other lists (lists of lists or multidimensional lists):

In [ ]:
list4 = [[1, 2], ["a", "b"]]

<br><br>
**Accessing elements of a list:**
Each element in a list has an index (it's place in the list). The first item in a list has index 0. Use square brackets `[]` and the element's index to access an element:
<br>
`list3[0]`

You can also subset a list by using the range of indicies, in the syntax:
<br>
`list3[staring_index : ending_index + 1]`

For the second index (the end of the range you are selecting), you must use the index of the *next* item following what you would like to select. Consider the following example:

In [ ]:
list5 = [0, 1, 2, 3, 4]
print("1st element of list5:", list5[0])
print("1st and 2nd elements of list5:", list5[0:2])
print("2nd through 4th elements of list5:", list5[1:4])

<div class="alert alert-block alert-info">
This +1 end index selection seems annoying at first. But realize that when you want to select the first `n` objects in a list, you can say:
<br>
<TT>list5[0:n]</TT>
</div>

<br><br>
**Reassigning elements of a list**:
we can change the elements of a list (thus, lists are called **"mutable"**, synonym for "mutatable"). Remember that indexing starts at 0 in python.

In [ ]:
print("Before we make changes:", list1)
list1[0] = 999

print("After we make changes: ", list1)

<br>
<div class="alert alert-block alert-warning">
<b>Aside about running chunks in jupyter notebooks:</b> What happens if we run just the chunk above again?
</div>

<br><br>

Note: Strings are basical lists of strings we can subset them

In [ ]:
s = "abcdefg"
print('s[1] =', s[1])
print('s[1] =', s[1:3])
print('s[1] =', s[1:6])

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___
#### Tuples
A `tuple` is basically an **immutable list**. The elements can be any python object but you cannot reassign new objects to an existing tuple.

In [ ]:
# Immutable iterable objects
tuple1 = (1, 2, 3)
tuple2 = 1, 2, 3
tuple3 = ("a", 23, [1, 2, 3])

Tuples are **"immutable"** so the elements of a tuple cannot be changed after creation. Lists are **"mutable"**, so their elements can be changed. Trying to change a tuple element results in an error:

In [ ]:
tuple1[0] = 999

<br><br>
However, you can reassign the name of a tuple to be a new tuple object

In [ ]:
# Create new tuple and reassign name tuple1 to it
tuple1 = (999, 2, 3)
# or
tuple1 = (999, tuple1[1], tuple1[2])

<br><br>

**Asside on python assignment (assigning values to an object):** python reads what's on the right side of an = sign before what is on the left. So you can reference "old" objects on the right while creating "new" objects. We can do this even if the new object is renaming the old object like above. This can be very confusing or very useful behavior.

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___
#### Ranges
A `range` is a kind of `generator` -- it creates elements one by one, as we ask for them. Used in a `for` loop, the generator will spit out the next element each time we iterate through the for loop. 

In [ ]:
range1 = range(5)   # kind of "list" of integers

print(range1)  # not very helpful at first

<br><br><br>

<div class="alert alert-block alert-info">
<b>For Loop Aside:</b> We'll be learning more about for loops in the next section. For now, just note that for loops allow us to run an operation for each element in an **iterable object**.
</div>


In [ ]:
for i in range1:
    print(i)

<br><br>
Note that `range` starts with the number 0 and ends **before 5**, not on 5. This results in a list of integers that still has 5 elements, but now with numbers that match python indexing. We can also make ranges that start in other places and count by numbers other than 1.

In [ ]:

range2 = range(10)
range3 = range(5, 10)     # start other than 0
range4 = range(2, 10, 2)  # skip by 2

for i in range4: print(i)

Ranges only take integers, not floats.

In [ ]:
range5 = range(2, 10.5)  # skip by 0.5

<br><br>
We cannot change any of the elements of a `range`, we can only request / view them. So a `range` is also **immutable**. It is a type of **immutable iterable object**.
<br><br>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___
#### Sets
Just like mathematical sets, sets cannot have repeated items. Can be useful for finding unique values of a list. We can use the `set()` function or just curly brackets `{}` to make a set.

In [ ]:
set1 = set([1,2,3])  # input to set() should be a list
print(set1)

set2 = {1,1,1,2,3}   # returns only unique values
print(set2)

<br><br>
All items / elements of a set must be immutable. You cannot add a list to a set. However, sets themselves are mutable objects and you can add or remove items from them. [More on adding and removing from sets](https://www.programiz.com/python-programming/set#:~:text=A%20set%20is%20an%20unordered,or%20remove%20items%20from%20it.)

In [ ]:
set2 = {1,1,1,2,3}
print("Starting set:", set2)

set2.add(4)  # Add one element
print("       Add 4:", set2)

set2.update([5,6])  # Add multiple elements using a list
print(" Adding 5, 6:", set2)

set2.discard(6)  # discard an element
print("Discarding 6:", set2)

set2.discard(6)  # can still discard an element if it doesn't exist in set
print("Discarding 6:", set2)

set2.remove(1)  # remove an element
print("  Removing 1:", set2)

set2.remove(1)  # removing an element that doesn't exist causes an Error
print("  Removing 1:", set2)



<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___
#### Dictionaries
Like a `set`, a `dict` also uses curly brackets, but uses `key:value` pairs. The key is on the left, and the value is on the right. This creates a type of unordered list where you can use a short key to acess something much larger or that might be changing. Just like looking up a the definition of a word in a physical dictionary.

In [ ]:
dict1 = {"key1": "this is my a value1", 
         'key2': 25, 
         3: 75, 
         4: [1,2,3]}

print("The keys in the dictionary are:", dict1.keys())
print("\n")

print('dict1["key1"] =', dict1["key1"])
print('dict1[3] =', dict1[3])

<br>Dictionaries are mutable, so we can change thier contents:

In [ ]:
print('dict1[4] =', dict1[4])  # print before

dict1[4] = [5, 4, 3]           # change
print('dict1[4] =', dict1[4])  # print after

<br>
<div class="alert alert-block alert-danger">
What if I call a key that doesn't exist?
</div>

In [ ]:
print(dict1[5])  # print a value for a key that does not yet exist

<br>
<div class="alert alert-block alert-success">
But I *CAN* create a new key:value pair that doesn't exist:
</div>

In [ ]:
dict1[5] = 25                  # Create new key:pair in dictionary
print('dict1[5] =', dict1[5])  # print it

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

___

### Getting an object's type
Everything in python is an "object." In python, all objects have metadata that describe what they are. For example, every object has a type like the types we described above. We can get this metadata by printing it out with the right syntax. Here, we can use the `type()` function to get the type of an object, then `print()` to print it out.

In [ ]:
print(type(int3))

print(type(float2))

<div class="alert alert-block alert-info">
<b>Printing an object's type can be super helpful when trying to debug <span style="color:red">errors</span>.</b>
</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>[top of page](#top)

<a id='numpy'></a>
## Part 4: Numpy Data Types
NumPy gives us the power to do faster and more mathematical operations in python:

>"NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more." [numpy.org](https://numpy.org/doc/stable/)


Let's take a quick look through...


### Basic Numpy Types
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Numpy type</p></th>
<th class="head"><p>C type</p></th>
<th class="head"><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.bool_" title="numpy.bool_"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.bool_</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">bool</span></code></p></td>
<td><p>Boolean (True or False) stored as a byte</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.byte" title="numpy.byte"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.byte</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">signed</span> <span class="pre">char</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.ubyte" title="numpy.ubyte"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.ubyte</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">char</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.short" title="numpy.short"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.short</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">short</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.ushort" title="numpy.ushort"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.ushort</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">short</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.intc" title="numpy.intc"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.intc</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">int</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.uintc" title="numpy.uintc"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.uintc</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">int</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.int_" title="numpy.int_"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.int_</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">long</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.uint" title="numpy.uint"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.uint</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">long</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.longlong" title="numpy.longlong"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.longlong</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">long</span> <span class="pre">long</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.ulonglong" title="numpy.ulonglong"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.ulonglong</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">long</span> <span class="pre">long</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.half" title="numpy.half"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.half</span></code></a> / <a class="reference internal" href="../reference/arrays.scalars.html#numpy.float16" title="numpy.float16"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.float16</span></code></a></p></td>
<td></td>
<td><p>Half precision float:
sign bit, 5 bits exponent, 10 bits mantissa</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.single" title="numpy.single"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.single</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">float</span></code></p></td>
<td><p>Platform-defined single precision float:
typically sign bit, 8 bits exponent, 23 bits mantissa</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.double" title="numpy.double"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.double</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">double</span></code></p></td>
<td><p>Platform-defined double precision float:
typically sign bit, 11 bits exponent, 52 bits mantissa.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.longdouble" title="numpy.longdouble"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.longdouble</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">long</span> <span class="pre">double</span></code></p></td>
<td><p>Platform-defined extended-precision float</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.csingle" title="numpy.csingle"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.csingle</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">float</span> <span class="pre">complex</span></code></p></td>
<td><p>Complex number, represented by two single-precision floats (real and imaginary components)</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.cdouble" title="numpy.cdouble"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.cdouble</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">double</span> <span class="pre">complex</span></code></p></td>
<td><p>Complex number, represented by two double-precision floats (real and imaginary components).</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.clongdouble" title="numpy.clongdouble"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.clongdouble</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">long</span> <span class="pre">double</span> <span class="pre">complex</span></code></p></td>
<td><p>Complex number, represented by two extended-precision floats (real and imaginary components).</p></td>
</tr>
</tbody>
</table>

From [numpy.org](https://numpy.org/doc/stable/user/basics.types.html)


<br><br>


<div class="alert alert-block alert-info">
These look familiar, but note that numpy.half / numpy.float16, numpy.single, numpy.double, and numpy.longdouble offer more and more decimals of precision.
</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

### Numpy Arrays
Arrays allow us to do vector operations in python. This will be covered in the next section. Let's take a quick look at how to construct numpy arrays.

#### Importing the NumPy Package
We're going to import the NumPy package, then rename it as `np` to make it shorter and easier to use.

In [2]:
import numpy as np

#### Using numpy
To use objects inside the numpy library, we use dot (.) notation. For example, to create a numpy array (like a mathematical vector), we will use `np.array()`. We'll get into more about python packages next section.

#### Creating Arrays from Lists

In [ ]:
# del(np)
import numpy as np

list1 = [1, 2, 3]
print('list1 =', list1)

array1 = np.array(list1)
print('array1 =', array1)


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

#### Mutli-demensional Arrays
We can create mutli-demensional arrays using a list of lists:

In [ ]:
list2 = [list1, list1, list1]
print('list2 =', list2)

array2 = np.array(list2)
print('array2 =\n', array2)

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

#### Adding to (appending) Arrays
We can add to arrays using the `np.append()` function.

In [ ]:
array3 = np.array([1])
print('array3 =', array3)

array3 = np.append(array3, 25)
print('array3 =', array3)

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>


#### Building Arrays
We can also build arrays inside for loops.

In [3]:
array4 = np.array([])

for i in range(10):
    array4 = np.append(array4, i)

print('array4 =', array4)

array4 = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Note that numpy arrays create numpy floats by default even if the inputs are integers. There are ways to specify integers if you need an array of integers instead.

<br><br><br><br><br><br><br><br><br><br>[top of page](#top)

<a id='matrix'></a>
## Part 5: Matrix Algebra in Python

Matrix algebra: pretty much every econometric problem has it and matrix algebra is often computationally MUCH faster than using loops (use julia if you can't stand to give up loops). In python, we primarily use NumPy arrays to do matrix multiplication.


Here's a good tutorial from Stanford in 2017: [start on page 19](https://web.stanford.edu/class/cs231a/section/section1.pdf) (beware that it uses python 2.7, not 3.8, but I think most still applies or has an easy update if you google it)

In [30]:
# Create a matrix M from lists
M = np.array([[1, 2],
              [4, 5],
              [7, 8]])

In [39]:
# Create a vector v
v1 = np.array([[1],
              [2],
              [3]])

v2 = np.array([1, 2, 3])

# note that we need an extra set of brackets to ma

<br><br>

Getting the shape / dimensions of an array (remember it's *rows x columns*)

In [31]:
print(M.shape)

(3, 2)


In [40]:
print(v1.shape)
print(v2.shape)  # no second dimension -- it's a flat array

(3, 1)
(3,)


In [41]:
print(v1 + v1)
print(3*v1)

[[2]
 [4]
 [6]]
[[3]
 [6]
 [9]]


In [42]:
# 3x3 Identity matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
# Vector indexing
v1[1]

array([2])

In [44]:
# Matrix indexing
print(M)

print(M[0])     # first row

print(M[0, 1])  # row 0, col 1 element

print(M[:2, 1:2])  # rows 0-1, col 1

[[1 2]
 [4 5]
 [7 8]]
[1 2]
2
[[2]
 [5]]


In [46]:
# Let's remember what M, v1, v2 look like
print(M)

[[1 2]
 [4 5]
 [7 8]]


In [47]:
print(v1)

[[1]
 [2]
 [3]]


In [48]:
print(v2)

[1 2 3]


In [52]:
# let's find v2.transpose * v2 (inner product?)
print(v2.T * v2)

[1 4 9]


<div class="alert alert-block alert-info">
NumPy implements this as <b>element-wise</b> multiplication
</div>


<br><br>

In [45]:
# What's M*v2?
print(M)
print(v2)

print(M.dot(v2))

[[1 2]
 [4 5]
 [7 8]]
[1 2 3]


ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

<br><br>
<div class="alert alert-block alert-danger">
<b>ValueError:</b> v2 is an array of shape (3,) -- it is a 1-dimensional array (a vector). In NumPy, we need to have "shape conformable arrays" to multiply. So we really need a 2-dimensional array (matrix) that only has one column.
</div>

In [59]:
# Both M and v1 are matrices, so they can be multiplied properly
print(M.shape)
print(v1.shape)

(3, 2)
(3, 1)


In [58]:
# How do we get them to multiply right?
print()

<br><br><br><br>

**Inverses**

In [66]:
M2 = np.array([[3, 0, 2],
               [2, 0, -2],
               [0, 1, 1]])

In [67]:
print(np.linalg.inv(M2))

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


**Determinants**

In [70]:
print(np.linalg.det(M2))

10.000000000000002


<br><br><br><br><br><br><br><br><br><br>

### Errors we've seen so far
- `KeyError`: dictionaries, removing an element from a set doesn't exist
- `TypeError`: tuple reassignment, non-integer input to range()
- `NameError`: package not yet imported
- `IndentationError`: improper indentation in code blocks
- `ValueError`: matrix dimensions not conforming

### Sites we've used
- [GeeksForGeeks](https://www.geeksforgeeks.org/python-programming-language/?ref=shm)
- [RealPython](https://realpython.com/)
- [W3 Schools](https://www.w3schools.com/python/)

### Other super useful sites when googling
- Stack Exchange
- Stack Overflow

<br><br><br><br><br><br><br><br><br><br>

## Looking Ahead
- Functions
- Python Classes
- Ethan's Python Class